### ISSUE TITLE
Question about sconstruct.log

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/template#109]
Hi gang,

I am playing around with the template for one of my projects. Can you let me know the most efficient way to send ```sconstruct.log``` to a different directory (e.g, ```/output```) rather than ```/release```?

I'm not asking for a template or package revision, just for a pointer on how best to implement in our current framework.

Thanks!

-Jesse

**Comment by Shun-Yang** [comment]
@jmshapir, I believe the location for `sconstruct.log` is customizable in our current framework. 

There is one line in `SConstruct` : 

```python

atexit.register(gs.log.end_log)

```
If you change it to 
```python

atexit.register(gs.log.end_log, release_dir='./output/')

```
then `sconstruct.log` will be stored in the given directory. 

Let me know if this solves your question.

**Comment by jmshapir** [comment]
Fixed! Thanks @Shun-Yang!

@SimonFreyaldenhoven fyi.
