### ISSUE TITLE
yaml.load(input) deprecated

### ISSUE THREAD

**Issue by qlquanle** [gslab-econ/template#110]
Hi all! 

yaml/pyyaml deprecated yaml.load() so I'm getting the following warning when I run the template:

```
../config/configuration.py:42: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFIG[key] = yaml.load(open(val, 'rU'))
```

The relevant documentation is here:

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation 

Please let me know if I can provide any more information!

**Comment by DavidRitzwoller** [comment]
The problem has been addressed and #113 is open for PR

**Comment by zkashner** [comment]
On older OS-es (such as my own) I believe that with python2, yaml is a system package and not possible to be upgraded. My installation of yaml does not have `FullLoader` so I have to revert this change locally. I am not sure what the best workaround is for this--but wanted to flag it.

**Comment by DavidRitzwoller** [comment]
@zan Is it not possible to use a different installation of python, say managed by anaconda?

**Comment by zkashner** [comment]
@DavidRitzwoller I ended up getting it to work (by replacing `Loader=yaml.FullLoader` with `Loader=yaml.SafeLoader`.)
It could be worth replacing `FullLoader` with `SafeLoader` as I believe that the functionality that we need from this `yaml` load should be included in `SafeLoader` and it will not cause older installs of python problems (and adds to ease of use and adoption to not need to have an anaconda version of python.) What do you think?

**Comment by DavidRitzwoller** [comment]
Thanks @zkashner. From my understanding of [this](https://github.com/yaml/pyyaml/issues/265) it seems like `SafeLoader` is the correct protocol for our context. So definitely agree that this seems smart to implement.
