### ISSUE TITLE
Improve SCons logging

### ISSUE THREAD

**Issue by gentzkow** [gslab-econ/template#2]
Our current SConstruct writes STDOUT to a log file /output/SConstruct.log.

I would like to improve this in 3 ways:

(1) We should write both STDOUT and STDERR

(2) We should write to the terminal *and* the log file, not to the log file alone

(3) We should write the log to the top-level directory rather than in /output/ and get rid of the SConstruct commands to test whether /output/ exists and create it if it doesn't. We should then use an [install builder](http://scons.org/doc/1.2.0/HTML/scons-user/c2848.html) to move the log file to the output directory in a final step.

**Comment by arosenbe** [comment]
Update, I have accomplished the first two objective and am working on the third. Currently, I am able to install the log file into the output directory, but the install builder works as a copy and not as a move. So after the installation, the log file remains in the top level of the directory. I have tried two unsuccessful methods of removing the top level log.

First, I tried a variety of ways to run the command `rm sconstruct.log`. They are unsuccessful because SCons executes all Python commands before executing SConscript and other built commands. 

Second, I tried to use the Delete Factory in a variety of built commands. These attempts have so far ended in dependency cycles or in no removal of the log file.

**Comment by gentzkow** [comment]
OK. Thanks.

Let's put no more than 1 hour more into trying to solve this. I get the
sense we are trying to do something that scons is really not designed to
do, and if that's the case we may want to rethink the goal.

**Comment by arosenbe** [comment]
Sounds good @gentzkow. I agree that we are pushing against the design of scons. I've seen advice for similar problems note that scons is a file builder, not a file remover. If I am unable to remove the top level log, is there a preference on how we treat it? I see three options, but perhaps you have a different idea.
  *  Produce the log in the top level and install a copy into `output/`
  *  Produce the log in the top level
  *  Produce the log directly in `output/`

**Comment by gentzkow** [comment]
I think the best option in that case would be to produce the log in the top
level and leave it there.

**Comment by lboxell** [comment]
@gentzkow,

 Any reason not to do a solution like [this](https://github.com/gslab-econ/template/blob/0f35898d6a44aec335be86bd23fcb621eb8579ea/SConstruct) for 3?

(Adding 'output/talk' to the source list is just to force this to be run after talk.)

**Comment by gentzkow** [comment]
Not a bad idea. It feels a little clunky to me because we have to remember
to add the last thing built as a source file; this won't be so clear and it
could be screwed up if build order ends up different for some reason. Also
I'm not sure about moving this file while we are still logging output to
it. (What would happen, e.g., if there was an error in the move step.

I don't think this is important enough to warrant a hack like this. Better
to keep things simple & clean.

**Comment by arosenbe** [comment]
In summary, this task handles the three improvements to scons logging in the following ways:

  1.  The stderr stream is redirected to the stdout stream
  2.  The `tee` command is used to write the combined stream to the terminal and a log on mac and linux. A windows implementation is handled in #5.
  3.  SCons does not have simple support for moving/removing an installed file. Instead, a single copy of the log is produced in the root of the repository.
