### ISSUE TITLE
Print .sconsign.dblite to human-readable sconsign.txt

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#22]
I have discovered that running

`sconsign .sconsign.dblite` 

print the file in a human readable format 

`sconsign .sconsign.dblite > sconsign.txt`

give you [this](https://gist.github.com/stanfordquan/f6aeddd027af6fc41064556a5379299c).

It's not super useful, but still quite useful as files have hash that you can use to track whether the most recent version was used to build other files.

Two things:

1) I suggest we integrate this line into the code so that it runs everytime we `scons`. This can be versioned if necessary.

2) The file seems to be machine-specific. I suspect this being the reason Scons force a rebuild every time I switch branches (@arosenbe and I have same issue) ? In that case, should we stop versioning this file? If so, does caching still work?

**Comment by stanfordquan** [comment]
so... :-1 ?

**Comment by lboxell** [comment]
@stanfordquan,

Sorry, I never responded on github. I think this will be useful, I just haven't had time to get back around to these lab tasks.

Will return once congress_text is wrapped up.

**Comment by lboxell** [comment]
Closing this task as the relevant issue is https://github.com/gslab-econ/gslab_python/issues/34.
