### ISSUE TITLE
Add license to template

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/template#24]

**Comment by lboxell** [comment]
@gentzkow @jmshapir,

We noticed that we currently don't have a license for the template, while I think we have licenses for the other public repos. I was just going to add the MIT license, but I wanted to check in to see what your thoughts were because if someone uses the template for their own project, it isn't quite clear whether they'd have to then license their project under the MIT license too (which seems undesirable).

**Comment by jmshapir** [comment]
given the language in the license I'm not concerned that it would have that effect but i am happy to defer to @gentzkow

**Comment by gentzkow** [comment]
I am not concerned either. Happy to proceed w/ license.
-- 

Matthew Gentzkow
Professor of Economics
Stanford University

**Comment by lboxell** [comment]
Sounds good.

Closing task.

Summary:
 - Added MIT license to template.
