### ISSUE TITLE
Familiarize yourself with template and gslab_python

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/template#36]
We are going to be doing a review of our template and [gslab_python](https://github.com/gslab-econ/gslab_python) shortly. It would be good to make sure you are familiar with both (particularly the gslab_scons portion of gslab_python).

While you're going through both, if you see things to improve or seem off, you can probably start making a list on this issue (as we'll be doing something similar shortly as a team).

**Comment by arosenbe** [comment]
We should use ZIP 64 compression in the release script. I ran into this as part of gslab-econ/congress_text#177.

**Comment by lboxell** [comment]
@meeranmismail,

I'm going to close this task because I think you have more important tasks currently open and there is probably low value for additional time spent on this at the moment.
