### ISSUE TITLE
Make readme more user-friendly

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/template#38]
The readme has become a little messy, to the point where it's difficult to track and install dependencies. The goal of this task is to spruce up the readme.

**Comment by arosenbe** [comment]
@lboxell, 

It doesn't look like all the statements in the readme are true, for example, homebrew is not the easiest way to install the Stata YAML parser. It seems like we might want to provide some more specific instructions for downloading, maybe adding the code in blocks.

**Comment by lboxell** [comment]
Fixed homebrew statement.

**Comment by lboxell** [comment]
I think we just want to point people to the source of the items being installed are (e,g., we don't need to tell people how to install Lyx, Lyx should tell people how to install Lyx.).

**Comment by lboxell** [comment]
Closing task.

Summary:
 - Made readme more explicit about yaml dependencies.
