### ISSUE TITLE
Implement 4.0 test comments for template

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/template#43]
See [template task]'s in https://github.com/gslab-econ/gslab_python/issues/58#issuecomment-295959587

Combined meeting notes:

Meeting note

- [x] Echo command for `user-config.yaml`. [Template task]

- [x] Allow stata-flavour yaml to be empty. Change stata-flavour to stata-exec. Make comment that Windows user can specify `StataMP-64.exe`. [Template task]

- [x] Prompt user input for yaml file if it does not exist. [Template task]

- [x] `setup.py` script name is not ideal in `template` (`setup.py` means something in the general Python context) [Template task]

- [x] drop default support for `gslab mtheme` [Template task]

- [x] It's not clear to me why we force the user to have a cache. We should at least discuss that if we make them write it into their `user-config`. (we decided to drop this as default requirement and add it as part of the "extra features" section in the readme.md) [Template task]

- [x] Remove demonstration of Stata/R, add it to FAQ (`build_stata` vs `build_python`) so forth [template task]

- [x] check_cache(cache_dir) [template task]
- [x] The entire error message in check_cache is not printed when there's an error. [template task]
- [x] fix use of `~` [template task]
- [x] don't produce .pyc [template task]
- [x] remove references to mode=release [template task]
- [x] GSLab specific import statement should be kept together at the top of the SConstruct. [template task]

**Comment by lboxell** [comment]
See https://github.com/gslab-econ/template/pull/45

**Comment by M-R-Sullivan** [comment]
**Summary**
- This issue passed PR in #45.
- Implemented miscellaneous changes to the template as listed [here](https://github.com/gslab-econ/template/issues/43#issue-223230365).
- Standardized `stata_executable` as name for the user's Stata executable in  gslab_python in gslab-econ/gslab_python#67. We also standardized it in `template.`
