### ISSUE TITLE
Team discussion of next steps

### ISSUE THREAD

**Issue by gentzkow** [gslab-econ/template#56]
Following release 4.0.0 of `template` and `gslab_python`, I would like us to do another team review to discuss next steps. The following is a list of proposed next steps I'd like us to consider. I would suggest that others add additional items they think should be considered then we schedule a call to discuss. 

* Raw / external data
    * All raw data in Dropbox raw data store; clear instructions in RA manual + directory template
    * Print manifest of contents of all external directories plus contents of provenance.log if exists (or specify other name)

* constants.yaml & user-config.yaml
    * propose to rename constants.yaml -> config-global.yaml and user-config.yaml -> config-user.yaml
    * Create config-user-template.yaml committed to repo; if config-user.yaml is missing build configuration_test.py copies from config-user-template.yaml

* Top-level reorganization
    * Separate top-level subs for /analysis/, and /paper-slides/
    * Follow standard export protocol to move release contents from one to /input/ sub of the next

* Reduce requirements, include optional languages
    * Make git-lfs optional; switch in config-global.yaml to require git-lfs
    * Make Stata, R, Lyx optional; switches in config-global.yaml to require
    * /analysis/source/R/ and /analysis/source/stata/; instructions for deleting those not being used; template set to require neither
    * /paper-slides/source/paper-lyx/ and /paper-slides/source/paper-latex/ 
    * Only true dependencies are python w/ gslab_python and scons

* Stata scripts
    * Default Stata executable is statamp on Mac/Linux and whatever it's supposed to be on Windows
    * We should go back to .do file templates in SVN and port over what we think is essential (e.g., prerequisites)
    * Minimal version of gslab_stata that we can require be installed; separate library that includes all our legacy commands
    * Need to define paths as globals rather than locals (otherwise can't call in subfunctions); probably need to create our own version of stata yaml

* Large output files
    * Put in /release/lg/

* minor
    * standardize underscore vs dash in filenames
    * state-of-repo.log should be in /release/ along with state-of-externals.log and sconstruct.log
    * Make gencat part of gslab_misc python tools
    * Stata tool for saving tables
    * Tables & figs hard coded in /source/paper/ Lyx files; not declared as dependencies
    * SConstruct
        * migrate debrief_env to constants.yaml?
        * how to cut down the amount of code here?
        * what does Default() command do?

**Comment by lboxell** [comment]
Collecting my comments here:
 - Make builders fail explicitly when targets are not build. See https://github.com/gslab-econ/template/issues/55.

**Comment by stanfordquan** [comment]
Collecting my comments here.

- Figure out a controlled environment for the general purpose `Command` builder. My instinct is to build a `Command` wrapper than runs whatever the user input as `command`, but use the logging machinery instead of the current free for all. That way we get timestamps.

**Comment by lboxell** [comment]
@royalTS, 

Feel free to add anything you've found confusing or that you think could be better implemented as you've played around with our template.

**Comment by RoyalTS** [comment]
Suggestions/comments/pointers from my side:

- I like the idea of making almost everything optional
- provide bash scripts to install all external dependencies (`brew install ...`
- I would switch to `Rscript` or `littlr` as the R command line interpreter. `R CMD BATCH` is outdated (https://stackoverflow.com/questions/21969145/why-or-when-is-rscript-or-littler-better-than-r-cmd-batch)
- the Python environment should be more tightly controlled. conda is the neatest approach to this but requires anaconda to be installed on the system. In its absence, `virtualenv`s and freezing them via `pip` may be the best option
- Have yet to find a truly great solution for more tightly controlling R packages and versions. `packrat`, `pacman` and `checkpoint` packages might all be options. No obvious best one among them.
- if you did want to create your own LaTeX builder, writing a thin wrapper around `latexmk` would probably get you pretty far
- and yes, a build failing when the targets didn't build seems like an absolutely essential feature of a build system

**Comment by gentzkow** [comment]
Let's do it sooner. Could you guys do 9:00 PT / 18:00 france time today?

**Comment by jmshapir** [comment]
i could probably do that

**Comment by lboxell** [comment]
@arosenbe @shun-yang @stanfordquan @yuchuan2016,

See above.

@gentzkow @jmshapir: That works for me if it works for everyone else.

---



On Aug 1, 2017, at 5:38 AM, jmshapir <notifications@github.com<mailto:notifications@github.com>> wrote:


i could probably do that

**Comment by lboxell** [comment]
Closing task. 

Summary:
 - We discussed the above points in a call today.
 - Created https://github.com/gslab-econ/admin/issues/115 to summarize the call and create the next steps.
