### ISSUE TITLE
Raw data provenance.log and revision checks

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#60]
#### Develop and document protocol for provenance.log when releasing data to Dropbox (6h)

* Determine whether releases to Dropbox should have the exact same `provenance.log` structure as raw data stored in dropbox, or some other derivative.
* Implement. 

#### Develop and implement protocol for logging external data assets. (8h) 

* Print contents of every provenance/checksum/readme/GH release hash from imported data into a log. Make sure the log is committed. 
    * Make sure the crawler we write doesn't go forever (use command line tools and subprocess in builder). 
    * Make sure the code is general enough for use with any sort of external dependency. 

#### Determine if we want to have automatic revision checks. (1h) 

* Determine whether it is feasible to specify a specific revision stable link on Dropbox.
* If not, is there some other way of approximating this behavior?
* Determine whether we want to implement this.
* Create new issue to implement if we want this feature.

**Comment by stanfordquan** [comment]
This should follow work on #59

**Comment by stanfordquan** [comment]
Suppose this is the situation

```   
                                           (1)
Raw A (DropBox) ---->  Derived A (GitHub) ----> Release A (DropBox) ----
  gslab_prov.log       gslab_derived.log         gslab_release_a.log    \           (2)
                                                                         ----> Analysis (GitHub) -----> Paper (GitHub)
                                                                        /       externals.log
                                                    Raw B (DropBox) ----
                                                    gslab_raw_b.log
```


where `ugly.log` is a log created by the original data provider, out of GSLab's control. The `gslab.log` files are created by us in some manners (after analysis/data manipulation). 

This task then has three parts: 

1) Implement `provenance.log` in step `(1)`. This will be some sort of caller for the `print_provenance()` @chuanyu develops in #59. The content of `provenance.log` should be discussed in conjunction with #59. Any deviation from that the protocol in raw data storage (as opposed to release) can be activated in `print_provenance()` using an argument.

2) Implement external logging in step `(2)`, i.e. create `externals.log`. So what should `externals.log` contain? Certainly `gslab_release_a.log` and `gslab_raw_b.log`. Do we want `gslab_derived.log` or `ugly.log`? If we do,
    
- Do we want `gslab_release_a.log` to already have `gslab_derived.log` appended? That way is the easiest, since then `externals_logger()` only have to search through `build/external` or other specified-external-directories for GSLab-approved provenance logs and then append. This means we call `externals_logger` at each step instead of just `(2)`. This is also as general as it can get: as long as the external resource has a `provenance.log`, we don't care how it was obtained. This will have to be extra conscious of size concern as to not have multiple copies. 
    
- If not, then we have to write a crawler that can go through (at least) GitHub/DropBox/SVN and check out the `external.log` file. This seems a lot harder than option 1, but do-able. 

3) 
    - Discuss with AR about the DropBox API and versioning.
    - If not, we can use the `provenance.log`. `provenance.log` should be a 1-1 mapping between the source code and the data. The checksum of the data serves as the build signature as well. If we want to go further, we could even archive the source code, `politext` style. `gslab_python` combined is 1mb. Source code zip + a checksum may serve the same purpose as the `provenance` Chuan proposed (although a bit less readable).

**Comment by yuchuan2016** [comment]
@stanfordquan , you are @-mentioning a wrong chuanyu...

**Comment by stanfordquan** [comment]
Um... 

Glad you got the notification anyway.  👯 👯‍♂️ 👯 👯‍♂️ 👯 👯‍♂️

**Comment by arosenbe** [comment]
See https://github.com/gslab-econ/template/issues/59#issuecomment-325856749

Comments on script
* [x] Switch section heading to ***
* [x] Print README before detailed file info
* [x] Implement line limit

<details>
  <summary> Click for update script </summary>

```python
import os
import sys
import datetime

import scandir # pip install scandir
import mmh3 # pip install mmh3

def make_provenance(start_path, readme_path, provenance_path, 
                    include_details = True, include_checksum = True, detail_limit = 10):
    file_details = determine_file_details(include_details, include_checksum)

    total_size, num_files, last_mtime, details = scan_wrapper(
        start_path, include_details, include_checksum, detail_limit, file_details)

    write_heading(start_path, provenance_path)
    write_directory_info(provenance_path, total_size, num_files, last_mtime)
    write_readme(readme_path, provenance_path)
    if include_details:
        write_detailed_info(provenance_path, details)
    

def determine_file_details(include_details, include_checksum):
    '''
    Determine if a checksum entry appears in the detailed file-level information.
    '''
    file_details = 'path|bytes|most recent modification time'
    if include_checksum:
        file_details = '%s|MurmurHash3' % file_details
    return [file_details]

def scan_wrapper(start_path, include_details, include_checksum, detail_limit, file_details):
    '''
    Walk through start_path and get info on files in all subdirectories.
    Walk in same order as os.walk. 
    Also scan to be recurisve-like without overflowing the stack on large directories. 
    '''
    total_size, num_files, last_mtime, file_details, dirs = scan(
        start_path, include_details, include_checksum, detail_limit, file_details)
    while dirs:
        new_start_path = dirs.pop(0) 
        total_size, num_files, last_mtime, file_details, dirs = scan(
            new_start_path, include_details, include_checksum, detail_limit, file_details, 
            dirs, total_size, num_files, last_mtime)
    return total_size, num_files, last_mtime, file_details

def scan(start_path, include_details, include_checksum, detail_limit, file_details,
         dirs = [], total_size = 0, num_files = 0, last_mtime = 0): 
    '''
    Grab file and create directory info from start path. 
    Also return list of unvisited subdirectories under start_path. 
    '''
    print start_path
    entries = scandir.scandir(start_path)
    for entry in entries:
        if entry.is_dir(follow_symlinks = False): # Store subdirs
            dirs.append(entry.path)
        elif entry.is_file():
            # Get file info
            path = entry.path
            stat = entry.stat()
            size = stat.st_size
            mtime = datetime.datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S')
            # Incorporate file info into directory info.
            total_size += size            
            num_files += 1
            last_mtime = max(last_mtime, mtime)
            # Optional detailed file information
            if include_details and (not detail_limit or num_files <= detail_limit): 
                line = '%s|%s|%s' % (path, size, mtime)
                if include_checksum:
                    with open(path, 'rU') as f:
                        checksum = str(mmh3.hash128(f.read(), 2017))
                    line = '%s|%s' % (line, checksum)
                file_details.append(line)
    return total_size, num_files, last_mtime, file_details, dirs

# May need to replace the \n with os.linesep for windows. 
def write_heading(start_path, provenance_path):
    '''
    Write standard heading for provenance: what and for where it is. 
    '''
    out = '*** GSLab directory provenance ***\ndirectory: %s\n' % os.path.abspath(start_path) 
    with open(provenance_path, 'wb') as f:
        f.write(out)

def write_directory_info(provenance_path, total_size, num_files, last_mtime):
    '''
    Write directory-level information to provenance. 
    '''
    out = 'total bytes: %s\n' % total_size + \
          'number of files: %s\n' % num_files + \
          'most recent modification time: %s\n' % last_mtime
    with open(provenance_path, 'ab') as f:
        f.write('\n*** Directory information\n')
        f.write(out)

def write_readme(readme_path, provenance_path):
    '''
    Writes readme to provenance.
    '''
    with open(readme_path, 'rU') as f:
        out = '%s' % f.read()
    with open(provenance_path, 'ab') as f:
        f.write('\n*** README verbatim\npath: %s\n' % os.path.abspath(readme_path))
        f.write(out)

def write_detailed_info(provenance_path, details): # Need to implement a line limit here.
    '''
    Writes file-level information to provenance.
    '''
    out = '%s\n' % '\n'.join(details)
    with open(provenance_path, 'ab') as f:
        f.write('\n*** File information\n')
        f.write(out)
```

**Comment by stanfordquan** [comment]
Solutions as of pull request gslab-econ/gslab_python#120

1) Releases to Dropbox has the same provenance.log structure as raw data stored in Dropbox. Releases to GitHub has additional GitHub-specific information (repo, branch, and release tag). Raise "sub-release" issue with PIs in meeting and suggest solutions (sub-directory name in github release tags).

2) Check with PIs:
    a) In template, do they prefer there to be a `provenance` produced by SCons or by `release`? Either way it would live in `./release` of a repository.

3) Revision stable link in DropBox is not supported out of the box, but we can write our own code that wraps various DropBox API methods to do that. It may not be necessary given our release protocol, which works like SVN "tag" directory.

**Comment by stanfordquan** [comment]
"Sub-release" issue:

- `release.py` does two things: 
    - zip a `./release` directory produced by `gslab_scons` and send it to a "local" release, herein after called Dropbox
    - signal GitHub to make a GitHub release, which involves GitHub zipping the repository (everything tracked by Git, which usually only exclude `build` and `release/lg`

Now that we have 2 SCons subdirectories in a repo, we can only make a "local" release when we're in one of these subdirs (analysis or papers/slides). This is bad because  on GitHub the release has both subdirs, but on Dropbox we only have one. 

Proposed solution: release tag has the subdir in front of it, i.e. releases `paper-v1` or `analysis-v2`.
