### ISSUE TITLE
Restructure top level YAML files

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#61]
* Change names to `config_user.yaml` and `config_global.yaml`. 
* Have a `config_user_template.yaml` that gets copied to `config_user.yaml` if the latter does not exist. 
* Determine how we prevents users from committing their person's `config_user.yaml` (don't spend much time on this).  
    * Commit the template file with a different filename, and discuss name changes in the readme. 
    * Add note in the readme telling users not to commit their own file. 
* Add comments to yaml files with specific instructions on what to put where. 
* Reflect change in code and documentation.

**Comment by Shun-Yang** [comment]
I will start on this after #72 pulled in.

**Comment by Shun-Yang** [comment]
Closing the task. Pull request is #74. Summary: I renamed and restructured the YAML files in the scons env.
