### ISSUE TITLE
Separate sub-directory for analysis and paper/slides 

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#62]
* Two subdirectories at top level: analysis and paper_slides. Each has its own SConsctruct and source, build, input, and release directories. 
* Tables and figures from analysis are installed in the input directory of paper_slides. 
    * Make sure the installation has a provenance (see raw data protocol). 
    * Is this input directory flat? 
    * how are paths specified from paper writing code to input directory?

**Comment by yuchuan2016** [comment]
Thread continues in #72.

**Comment by yuchuan2016** [comment]
Merged in #72. Summary:
- Have two top-level directories: `analysis` and `paper_slides`. Each sub-directory has its own `constants.yaml`, `configuration_test.py`, `SConstruct`, and `source - build - release` structure.
- In `analysis/source`, we delete `raw` and `analysis` directories, and add directories with informative names. 
- In `analysis`, we release plain table text files and `eps/pdf` figures in `release`.
- We manually copy files in `analysis/release` to `paper_slides/input`.
- The two top-level directories are self-contained. We do all analysis under `analysis`, and fill tables, wrap figures, and build paper and slides in `paper_slides`.
