### ISSUE TITLE
Make current dependencies optional

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#63]
* The only true dependencies are Python (2.7.X), GSLab Python (4.1.0), PyYAML, and SCons. 
* Create switches to implement our automated checks of other software and run example scripts. 
    * Comment out lines in SConstruct or SConscript. 
    * Add instructions on turning on dependencies in readme.

**Comment by yuchuan2016** [comment]
I think git-lfs is also a true dependency. Without git-lfs, we even cannot clone this repo.

Some other things:
- Shall we make `lyx` also a true dependency? I would vote for yes. We need at least one of `lyx`/`tex` to run `paper_slides` directory. We can say in README that users can turn off `lyx` and turn on `tex`, but the default one is `lyx`. (The default software for `analysis` directory is `python`)
- Shall we write `check_matlab` and `check_latex` in `configuration_test.py` now?
- Shall we write scanner for `latex`, similar to [`lyx`](https://github.com/gslab-econ/gslab_python/blob/d01d40d50e8c74ca0b4c4d99f5a38d7d83b22e2d/gslab_scons/misc.py#L240) now?

@stanfordquan @Shun-Yang , FYI if you have any opinion on above.

**Comment by Shun-Yang** [comment]
My suggestion is to make `git-lfs` and `lyx` as dependency, and postpone writing `check_matlab`, `check_latex` and `latex_scanner` to the end and see if we have time in this sprint to finish them. Of course, if you think they are relatively easy to do, then feel free to get this done now.

**Comment by stanfordquan** [comment]
I vote making a note and delaying `check_matlab` and `check_latex`, same for `latex_scanner`. I vote making `TeX` a dependency over `LyX` (smaller footprint, and a lot more people use TeX anecdotally). I think PIs may prefer `LyX` though.

**Comment by yuchuan2016** [comment]
Another potential problem is, if users simply write a Stata do file without turning on the stata dependency in `config_global.yaml` (say, if they uncomment the stata block in `analysis/source/prepare_data/SConcsript`, then `configuration_test` won't check stata requirements. Then the build may fail. This may violate the spirit that we want to catch all errors before users actually run the code.

**Comment by yuchuan2016** [comment]
@gentzkow , per team discussion, we have several options to specify software dependencies. We want your opinion over these options.

- Use the current structure. Specify dependencies in [`config_global.yaml`](https://github.com/gslab-econ/template/blob/7529e71e04591eb9fd0a5683e112ff1b0cd6d224/analysis/config_global.yaml). Check requirements only for softwares that have an entry Yes. The disadvantage is users may not be conscious enough to change it when using a new software.
- Add checks as a part of the builders when they are defined in `SConstruct` by `Builder(action = gs.build_xx)`. Comment out lines that are not required. If a user want to use another builder, they need to uncomment the relevant line, and the builder will automatically do the check.
- Check the extensions of scripts in the repo that will be executed. Turn of the dependencies accordingly. This may involve a decent amount of work.

**Comment by gentzkow** [comment]
Thanks.

The second option sounds good to me if it can work robustly (i.e., if I uncomment a builder and the software isn't installed I'll always get a nice error; if I don't uncomment a builder but try to run steps that require that software I get an error as well (maybe a bit less nice))

**Comment by gentzkow** [comment]
(Otherwise, first option is fine)

**Comment by yuchuan2016** [comment]
Pull request created in #78.
