### ISSUE TITLE
Port example scripts to multiple languages

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#64]
* Port template code for Stata, R, Python, MATLAB, etc. from SVN (perhaps with slight modifications).
    * Code should conform to our style guides. 
    * Use gslab_stata functions to export Stata tables. `preliminaries` for Stata.
* Each subdirectory has same implementation coded in multiple languages. 
    * Determine if LyX and LaTeX follow this convention or are in separate paper_slides_lyx and paper_slides_Llatex subs.

**Comment by stanfordquan** [comment]
Subdirectories should be flat, code should not run by default but easily switched on in Sconscript. Only need ported code in one subdirectory

**Comment by yuchuan2016** [comment]
Summary:
- Add sample scripts for Stata, python, R and Matlab in `analysis/source/prepare_data` and `analysis/source/descriptive`.
- Add sample input for lyx and latex in `paper_slides/source/paper`.
- Make `python` as the only required language in `analysis` and `lyx` the required software in `paper_slides`. Mute the rest in `config_global.yaml` and `SConscripts`.

Pull in #76.
