### ISSUE TITLE
Explore solutions for automatic (simpler) dependency installation.

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#65]
* Examine python virtual environments (e.g., `conda`) and related tools in R (e.g., `packrat`). 
* Find what works and what gets done in practice. 
* Don't include any systems in this round, but make note of them for larger projects with many dependencies.

**Comment by arosenbe** [comment]
@stanfordquan, @yuchuan2016, and @Shun-Yang

Could you take a look at [my first pass at the deliverable](https://github.com/gslab-econ/template/blob/a56aad014452518b8c1887da18e4e8226ca68345/issues/issue65.md)?

**Comment by arosenbe** [comment]
Balled into #63. We went with scripts in a top-level `config` directory to track and install dependencies.
