### ISSUE TITLE
Force integration with gslab_stata

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#66]
* Force installation of all our stata ado files by default if using Stata in a repo. 
    * Document in readme which ones are necessary and how this prerequisite can be changed. 
* Create our own YAML parser that stores variables as globals. Profusely acknowledge prior parser.

**Comment by yuchuan2016** [comment]
@stanfordquan @Shun-Yang , to create the YAML parser that stores variables as globals, I only change a few words in the original `ado` file (basically change `local` to `global`). Should we make it a part of [`gslab_stata`](https://github.com/gslab-econ/gslab_stata/)? But according to https://github.com/gslab-econ/gslab_stata/pull/4#issuecomment-314199928, we only want to keep those ado files produced ourselves in that repo. Modifying a few words won't fall into this. If not, do you have idea on how we want to install it?

**Comment by yuchuan2016** [comment]
Never mind. We can just modify `yaml` in [stata-misc](https://github.com/gslab-econ/stata-misc).

**Comment by yuchuan2016** [comment]
Summary:
- Add `preliminaries` and `matrix_to_txt` in Stata example script.
- Add `preliminaries` and matrix_to_txt` in configuration test.
- Modify the yaml file to store path in globals [here](https://github.com/gslab-econ/stata-misc).

Pull in #77.
