### ISSUE TITLE
Replace hyphens with underscores everywhere

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#68]
Do this in **both** template and gslab_python.

Hyphens are not valid characters in object names in Python and R. We thus prefer underscores. 

Make the change everywhere and document in RA Manual.

**Comment by stanfordquan** [comment]
There's no non-language/non-url hyphen-to-underscores change necessary in gslab_python and template (except for `user-config.yaml` which will be dealt with in #61) (except for `gslab-econ` and existing repo names). 

I made two changes in the RA-manual.

1) Branch names should use exclusively underscores. 

2) New repo should use exclusively the lowercase alphabet and underscores. I decide that it's too much of a hassle to change current repo names, even if it's currently an annoying mish-mash of hyphen/underscore.

@Shun-Yang can you please confirm these changes quickly then we can close this. Thanks!

**Comment by Shun-Yang** [comment]
@stanfordquan , confirmed!

**Comment by stanfordquan** [comment]
Thanks!
