### ISSUE TITLE
Find and integrate YAML tool for MATLAB

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#70]
## YAML MATLAB tool 

How do we read YAML config files in MATLAB? 

#### Explore, select, and incorporate a MATLAB YAML parser (8h) 

* See notes in [here](https://github.com/gslab-econ/template/issues/56#issuecomment-318457357)
* Survey the options. 
* Pick the best. 
* Include it in our MATLAB scripts.

**Comment by Shun-Yang** [comment]
Following is my deliverable: 

### Summary: 

There are not many Yaml parser for MATLAB. I have found following ones: 
- https://code.google.com/archive/p/yamlmatlab/
- https://github.com/biogeo/mat-yaml
- http://vision.is.tohoku.ac.jp/~kyamagu/software/yaml/

There is little documentation on all of these. However, the first link appears to be the most popular one (see [here](https://stackoverflow.com/questions/10017298/read-yml-files-in-matlab)) and also the one Levi uses in gslab-econ/divergence#17.  I don't expect that we need much complicated functionality on this tool, and therefore my suggestion is simply going with https://code.google.com/archive/p/yamlmatlab/.

**Comment by Shun-Yang** [comment]
@stanfordquan , again, if you agree, I will go ahead and incorporate this to gslab_matlab.

**Comment by stanfordquan** [comment]
Sounds good to me.

**Comment by Shun-Yang** [comment]
Closing the task. Pull request is created [here](https://github.com/gslab-econ/gslab_matlab/pull/4). 
Summary: investigated and incorporated a MATLAB yaml parser and also restructured `gslab_matlab` repo a little.
