### ISSUE TITLE
 Migrate gencat to gslab_misc

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#71]
see title

**Comment by Shun-Yang** [comment]
Quick question: where is `gslab_misc`?

**Comment by stanfordquan** [comment]
Maybe `gslab_python` `misc`? @arosenbe

**Comment by arosenbe** [comment]
@Shun-Yang, my understanding was that gslab_misc is a not-yet-created subdirectory of gslab-python, following the [svn setup](https://econ-gentzkow-svn.stanford.edu/repos/main/trunk/lib/python/).

**Comment by Shun-Yang** [comment]
Closing the task. Pull request is at gslab-econ/gslab_python#116. Summary: migrated gencat to gslab_python/gslab_misc.
