### ISSUE TITLE
Test symlink with scons cache

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/template#9]
Test using a symlink to some shared drive (such as hsfiles) that is mounted locally as the cache.

**Comment by lboxell** [comment]
@M-R-Sullivan,

Could you check this at some point when you get the chance? 

Steps:
 - Mount hsfiles to mac. (Username should be `WIN\[SUNetID]` and pass should be pass for SUNetID
 - Symbolically link 'cache' directory in hsfiles(should be `/Volumes/economics/cache` to `/Users/$USER/hsfiles_cache`
 - Checkout `issue9_symlinkcache` template branch and run `scons mode=cache`. 
 - If everything works correctly, scons should just pull the build file from the cache. 
 - Move `build/data/data.txt` to `build/data/data_real.txt`
 - Create symbolic link from `build/data/data_real.txt` to `build/data/data.txt`
 - Run `scons`
 - If everything works correct, scons should not rebuild anything.

This shows two things:
 - Implementation of using hsfiles for caching and using a symbolic link to the cache.
 - For scons, the hash of a symbolic link is the same as the hash of the original file. (You can also do `md5 data.txt` and `md5 data_real.txt` in terminal to compare the md5 hash that mac os will give you for each. Spoiler: they are the same.).

**Comment by M-R-Sullivan** [comment]
@lboxell - Indeed. I should have time to do this momentarily.

**Comment by M-R-Sullivan** [comment]
@lboxell - I did the above an got the following error when running scons after creating the symbolic link:

```bash
scons: Reading SConscript files ...
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
Calls: main -> write.table -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'build/data/data.txt': No such file or directory
Execution halted
scons: done reading SConscript files.
scons: Building targets ...
Rscript source/data/build.R > build/data/sconscript.log
scons: *** [build/data/data.txt] Error 1
scons: building terminated because of errors.
```
 
Let me know if you'd like to see my directory or if it would be helpful if I worked through your steps again.

**Comment by lboxell** [comment]
@M-R-Sullivan,

To confirm, you got these errors after: Create symbolic link from `build/data/data_real.txt` to `build/data/data.txt`?

So the first step with hsfiles worked correctly?

The only thing I can think of right now without seeing the directory myself is to just check and see if it looks like the symbolic link for data.txt was created correctly.

**Comment by M-R-Sullivan** [comment]
@lboxell - I got them after "Run `scons`". Yes, data.txt was successfully fetched from the cache. 

The problem was that data.txt wasn't functioning as a link to data_real.txt after I ran:
```bash
mv build/data/data.txt build/data/data_real.txt
ln -s build/data/data_real.txt build/data/data.txt 
```

yet the following did correctly establish the link:
```
mv build/data/data.txt build/data/data_real.txt
cd build/data
ln -s data_real.txt data.txt 
cd ../..
```

I have no explanation for this behaviour yet. However after setting up the link from data.txt to data_real.txt, `scons` ran without rebuilding anything.

**Comment by lboxell** [comment]
@M-R-Sullivan,

I just tested the following: 
```
mv build/data/data.txt build/data/data_real.txt
ln -s data_real.txt build/data/data.txt
``` 
which also works. So I think the issue is that the first path should be a relative path from the folder of the second file. 

Thanks for checking this. Since this was mostly exploration, I don't think we need to any further PR, unless you disagree with any of my conclusions in https://github.com/gslab-econ/template/issues/9#issuecomment-249027092.

**Comment by M-R-Sullivan** [comment]
@lboxell - Ah. That's good to know. 

I agree re: PR. I don't disagree with your conclusions.

**Comment by lboxell** [comment]
@gentzkow,

This was something you wanted to know about at some point. 

This task shows two things:
 - Implementation of using hsfiles for caching and using a symbolic link to the cache. For projects that are all run on local iMacs at Stanford (i.e., no clusters and nobody really VPN'ing), hsfiles might be a nicer solution than Drive for the cache because I think there are less ownership issues and manual steps (such as moving files from 'shared with me' to 'my drive'). Mounting hsfiles and sym linking also doesn't take up hard drive space to my understanding. 
 - For scons, the hash of a symbolic link is the same as the hash of the original file. 

I'll close and delete the [branch](https://github.com/gslab-econ/template/commit/3ee848a1e1f18b0c6a09a26973995c7ad7effa60) unless there is something else that you wanted to know.

Outline: https://github.com/gslab-econ/template/issues/9#issuecomment-249027092

**Comment by gentzkow** [comment]
Thanks. This sounds promising. When we revisit we will want to think about how this would work on Windows and whether there's a good workflow that would let us sync from hsfiles to clusters etc.

**Comment by lboxell** [comment]
Closing task.

Summary: https://github.com/gslab-econ/template/issues/9#issuecomment-249320037
