### ISSUE TITLE
Evaluate switch to SCons 3

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/template#95]
SCons is currently on release 3.0.1. We're using 2.5.1, and that's behind by one major and one minor release. The goal of this task is to decide if we want to stick at 2.5.1 or update. 

* [Release notes](http://scons.org/RELEASE.txt)
* [Change log](http://www.scons.org/CHANGES.txt)

I don't think this would be a difficult change, since we can just drop in the newer scons local archive. 

My sense is that most of the changes aren't relevant to us, with the possible exception of 
> 3.0.0 should be slightly faster than 2.5.1.  Changes yielded a 15% speed up for null incremental builds.

Thoughts?

**Comment by lboxell** [comment]
My comments:

 - Looks like python3 is supported. That was one thing we had on the outline to reconsider once scons supported it.
 - Might cause rebuilds, but shouldn't be too much of an issue.
 - Didn't see any obvious reason not to.

**Comment by Shun-Yang** [comment]
I agree with @lboxell. I don't see any reason not to switch.

**Comment by yuchuan2016** [comment]
Agree!

**Comment by arosenbe** [comment]
Update made and under PR at #97 by @Shun-Yang.
