### ISSUE TITLE
4.1.0 template issues

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/template#99]
Hi @stanfordquan,

I checked out the template to help @zkashner on his practice task and am having some issues following the steps listed in the readme. See my output below: 
> DN0a1e6122:Research Levi1$ rm -rf template/
DN0a1e6122:Research Levi1$ git clone -b 4.1.0 git@github.com:gslab-econ/template.git
Cloning into 'template'...
remote: Counting objects: 2751, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 2751 (delta 3), reused 8 (delta 3), pack-reused 2738
Receiving objects: 100% (2751/2751), 4.02 MiB | 3.74 MiB/s, done.
Resolving deltas: 100% (1082/1082), done.
Checking connectivity... done.
Downloading config/scons.zip (648.17 KB)
Downloading paper_slides/release/paper/ondeck.pdf (17.57 KB)
Downloading paper_slides/release/paper/online_appendix.pdf (44.59 KB)
Downloading paper_slides/release/paper/paper.pdf (57.72 KB)
Downloading paper_slides/release/paper/text.pdf (17.57 KB)
Downloading paper_slides/release/talk/slides.pdf (29.26 KB)
Checking out files: 100% (50/50), done.
DN0a1e6122:Research Levi1$ cd template/
DN0a1e6122:template Levi1$     python config/config_python.py

>Collecting git+http://git@github.com/gslab-econ/gslab_python.git@v4.1.0
  Cloning http://git@github.com/gslab-econ/gslab_python.git (to v4.1.0) to /private/var/folders/9n/r307fbt12rjfch7x2cc3v5k00000gp/T/pip-VWFVOA-build
  Could not find a tag or branch 'v4.1.0', assuming commit.
error: pathspec 'v4.1.0' did not match any file(s) known to git.
Command "git checkout -q v4.1.0" failed with error code 1 in /private/var/folders/9n/r307fbt12rjfch7x2cc3v5k00000gp/T/pip-VWFVOA-build 

Note sure what the issue here is because I'm not familiar with the new 4.1.0 features in template or gslab_python. (Feel free to re-assign as you see fit, I just saw you were on the 4.1.0 review.)

**Comment by arosenbe** [comment]
@lboxell, please see #94.

**Comment by lboxell** [comment]
Thanks, @arosenbe! Closing the task.
